### PR TITLE
MNT: Re-rendered with conda-build 3.18.9, conda-smithy 3.5.0, and con…

### PR DESCRIPTION
**Pull request by ihnorton**
…da-forge-pinning 2019.10.01

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ihnorton** [comment]
@conda-forge-admin, please rerender

**Comment by ihnorton** [comment]
The build failure described in PR #10 has been fixed, by telling cmake that the anaconda compiler has the requested feature (x-ref more description in https://github.com/conda-forge/conda-forge.github.io/issues/785#issuecomment-538438705).

However, the linux build has hung 3x, with the message `Waiting for console output...`. I have locally built the recipe successfully on linux, with conda build so not sure what the issue is.

**Comment by ihnorton** [comment]
I also added a commit proposing myself and @Shelnutt2 as maintainers (I maintain several other packages, and we will both be active users of this one, assuming the build fixes go through and are usable). If this is a problem, let me know and I'll take it out.

**Comment by frol** [comment]
@ihnorton Thank you for the fixes! Welcome to the maintainers team!

**Pull request merged**
